const mongoose = require("mongoose");

const mobileVerificationSchema = new mongoose.Schema({
    mobileNumber: {
        type: String,
        required: true,
    },
    sessionId: {
        type: String,
        required: true,
    },
    otp: {
        type: String,
        required: false, // OTP is generated by 2Factor, so we might not store it here. But keeping it optional just in case.
    }
}, { timestamps: true });

module.exports = mongoose.model("MobileVerification", mobileVerificationSchema);
